export const biomotorAbilitiesToChoose = [
  {
    name: 'Supramaximal Strength',
    intensity: 'more than 100% 1RM',
    duration: '<6s',
    energySystem: 'ATP-PC system',
    contribution: '100% Anaerobic Alactic',
  },
  {
    name: 'Strength',
    intensity: '85-100% 1RM',
    duration: '<6s to 30s',
    energySystem: 'ATP-PC system/Fast glycolysis',
    contribution: '100% Anaerobic Alactic',
  },
  {
    name: 'Power - bodyweight',
    intensity: '70-85% 1RM',
    duration: '<6s to 30s',
    energySystem: 'ATP-PC/Fast glycolysis',
    contribution: '95-100% Anaerobic Alactic',
  },
  {
    name: 'Power - light Ballistics',
    intensity: '70-85% 1RM',
    duration: '<6s to 30s',
    energySystem: 'ATP-PC/Fast glycolysis',
    contribution: '95-100% Anaerobic Alactic',
  },
  {
    name: 'Power - medium Ballistics',
    intensity: '70-85% 1RM',
    duration: '6s to 30s',
    energySystem: 'ATP-PC/Fast glycolysis',
    contribution: '80-95% Anaerobic Alactic to Anaerobic Lactic',
  },
  {
    name: 'Power - heavy Ballistics',
    intensity: '70-85% 1RM',
    duration: '<6s to 30s',
    energySystem: 'ATP-PC/Fast glycolysis',
    contribution: '95-100% Anaerobic Alactic',
  },
  {
    name: 'Hypertrophy light',
    intensity: '65-75% 1RM',
    duration: '30s to 2min',
    energySystem: 'Fast glycolysis',
    contribution: '50-80% Anaerobic Lactic',
  },
  {
    name: 'Hypertrophy medium',
    intensity: '75-85% 1RM',
    duration: '30s to 2min',
    energySystem: 'Fast/Slow glycolysis',
    contribution: '50-80% Anaerobic Lactic',
  },
  {
    name: 'Muscular Endurance',
    intensity: '50-65% 1RM',
    duration: '>3min',
    energySystem: 'Oxidative',
    contribution:
      '40-95% Aerobic with some Anaerobic Lactic in shorter durations',
  },
  {
    name: 'Hypertrophy heavy',
    intensity: '80-90% 1RM',
    duration: '30s to 2min',
    energySystem: 'Fast/Slow glycolysis',
    contribution: '50-95% Anaerobic Lactic',
  },
  {
    name: 'Hypertrophy - bodyweight',
    intensity: 'BW',
    duration: '30s to 2min',
    energySystem: 'Slow glycolysis/Oxidative',
    contribution: '50-60% Aerobic with some Anaerobic Lactic',
  },
  {
    name: 'Mobility',
    intensity: '',
    duration: 'Varies',
    energySystem: 'Oxidative',
    contribution: '',
  },
];

export const toolsForTrainingUsage = [
    'barbell',
    'landmine',
    'safety bar',
    'trap bar',
    'dumbells',
    'dumbell',
    'ketlebells',
    'kettlebell',
    'gymnastic rings',
    'pull-up bar',
    'dips bars',
    'parelettes',
    'medicine ball',
    'swiss ball',
    'bicycle',
    'bodyweight',
  ];
  